M48
; DRILL file {KiCad 8.0.4} date 2025-04-28T15:50:53-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-28T15:50:53-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0417
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1299
%
G90
G05
T1
X6.0663Y-3.0134
X6.1063Y-2.8134
X6.1463Y-3.0134
T2
X6.0709Y-3.2165
T3
X6.2709Y-3.2756
T4
X4.9606Y-3.5085
X4.9606Y-3.9585
M30
